## Situación Problema 2 

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Cargar el archivo CSV en un DataFrame
data = pd.read_csv("/Users/tonitojuarez/Downloads/ckd.csv")

# Obtener los nombres de las columnas
column_names = data.columns

# Inicializar listas para almacenar nombres de variables continuas y categóricas
variables_numericas = []
variables_categoricas = []

# Analizar el tipo de dato de cada columna
for column_name in column_names:
    column_type = data[column_name].dtype

#Si el tipo de dato es numérico, agregar a la lista de variables numericas
    if pd.api.types.is_numeric_dtype(column_type):
        variables_numericas.append(column_name)
#Si el tipo de dato no es numérico, agregar a la lista de variables categóricas
    else:
        variables_categoricas.append(column_name)

# Imprimir las listas de variables continuas y categóricas
print("Variables numericas:", variables_numericas)
print("Variables categóricas:", variables_categoricas)

Variables numericas: ['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']
Variables categóricas: ['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']


In [3]:
data.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [4]:
#Variables categóricas
df = data[['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']]
df.head()

rbc        pc         pcc          ba  htn   dm cad appet   pe  ane  \
0     NaN    normal  notpresent  notpresent  yes  yes  no  good   no   no   
1     NaN    normal  notpresent  notpresent   no   no  no  good   no   no   
2  normal    normal  notpresent  notpresent   no  yes  no  poor   no  yes   
3  normal  abnormal     present  notpresent  yes   no  no  poor  yes  yes   
4  normal    normal  notpresent  notpresent   no   no  no  good   no   no   

  classification  
0            ckd  
1            ckd  
2            ckd  
3            ckd  
4            ckd

In [5]:
#Variables numéricas
data = data[['id', 'age', 'bp', 'sg', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo','pcv', 'wc', 'rc']]
data.head()

id   age    bp     sg   su    bgr    bu   sc    sod  pot  hemo pcv    wc  \
0   0  48.0  80.0  1.020  0.0  121.0  36.0  1.2    NaN  NaN  15.4  44  7800   
1   1   7.0  50.0  1.020  0.0    NaN  18.0  0.8    NaN  NaN  11.3  38  6000   
2   2  62.0  80.0  1.010  3.0  423.0  53.0  1.8    NaN  NaN   9.6  31  7500   
3   3  48.0  70.0  1.005  0.0  117.0  56.0  3.8  111.0  2.5  11.2  32  6700   
4   4  51.0  80.0  1.010  0.0  106.0  26.0  1.4    NaN  NaN  11.6  35  7300   

    rc  
0  5.2  
1  NaN  
2  NaN  
3  3.9  
4  4.6

In [6]:
data = data[data['rc'] != '\t?']
data['rc'] = data['rc'].astype(float)
data['rc'].unique()

array([5.2, nan, 3.9, 4.6, 4.4, 5. , 4. , 3.7, 3.8, 3.4, 2.6, 2.8, 4.3,
       3.2, 3.6, 4.1, 4.9, 2.5, 4.2, 4.5, 3.1, 4.7, 3.5, 6. , 2.1, 5.6,
       2.3, 2.9, 2.7, 8. , 3.3, 3. , 2.4, 4.8, 5.4, 6.1, 6.2, 6.3, 5.1,
       5.8, 5.5, 5.3, 6.4, 5.7, 5.9, 6.5])

In [7]:
data['wc'].replace(['\t6200', '\t8400'], ['6200','8400'], inplace = True)
data = data[data['wc'] != '\t?']
data['wc'] = data['wc'].astype(float)
data['wc'].unique()

array([ 7800.,  6000.,  7500.,  6700.,  7300.,    nan,  6900.,  9600.,
       12100.,  4500., 12200., 11000.,  3800., 11400.,  5300.,  9200.,
        6200.,  8300.,  8400., 10300.,  9800.,  9100.,  7900.,  6400.,
        8600., 18900., 21600.,  4300.,  8500., 11300.,  7200.,  7700.,
       14600.,  6300.,  7100., 11800.,  9400.,  5500.,  5800., 13200.,
       12500.,  5600.,  7000., 11900., 10400., 10700., 12700.,  6800.,
        6500., 13600., 10200.,  9000., 14900.,  8200., 15200.,  5000.,
       16300., 12400., 10500.,  4200.,  4700., 10900.,  8100.,  9500.,
        2200., 12800., 11200., 19100., 12300., 16700.,  2600., 26400.,
        8800.,  7400.,  4900.,  8000., 12000., 15700.,  4100.,  5700.,
       11500.,  5400., 10800.,  9900.,  5200.,  5900.,  9300.,  9700.,
        5100.,  6600.])

In [8]:
data['pcv'].replace(['\t43'], ['43'], inplace = True)
data = data[data['pcv'] != '\t?']
data['pcv'] = data['pcv'].astype(float)
data['pcv'].unique()

array([44., 38., 31., 32., 35., 39., 36., 33., 29., 28., nan, 16., 24.,
       37., 30., 34., 40., 45., 27., 48., 52., 14., 22., 18., 42., 17.,
       46., 23., 19., 25., 41., 26., 15., 21., 43., 20., 47.,  9., 49.,
       50., 53., 51., 54.])

In [9]:
data = data[['age', 'bp', 'sg', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo','pcv','wc','rc']]
data.head()

age    bp     sg    bgr    bu   sc    sod  pot  hemo   pcv      wc   rc
0  48.0  80.0  1.020  121.0  36.0  1.2    NaN  NaN  15.4  44.0  7800.0  5.2
1   7.0  50.0  1.020    NaN  18.0  0.8    NaN  NaN  11.3  38.0  6000.0  NaN
2  62.0  80.0  1.010  423.0  53.0  1.8    NaN  NaN   9.6  31.0  7500.0  NaN
3  48.0  70.0  1.005  117.0  56.0  3.8  111.0  2.5  11.2  32.0  6700.0  3.9
4  51.0  80.0  1.010  106.0  26.0  1.4    NaN  NaN  11.6  35.0  7300.0  4.6

Ahora si ya tenemos la base de datos con todas las columnas tipo float

In [10]:
column_names = data.columns
for column_name in column_names:
    print(data[column_name].dtype)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


Ya podemos renombrar las variables para entender que son

In [11]:
data = data.rename(columns={'age':'Edad','bp':'Presion', 'sg': 'Gravedad','bgr':'Glucosa','bu':'Urea','sc':'Creatinina','sod':'Sodio','pot':'Potasio','hemo':'Hemoglobina','pcv':'Packed cell volume','wc':'White blood cell count','rc':'Red blood cell count'})
                            
data.head()

Edad  Presion  Gravedad  Glucosa  Urea  Creatinina  Sodio  Potasio  \
0  48.0     80.0     1.020    121.0  36.0         1.2    NaN      NaN   
1   7.0     50.0     1.020      NaN  18.0         0.8    NaN      NaN   
2  62.0     80.0     1.010    423.0  53.0         1.8    NaN      NaN   
3  48.0     70.0     1.005    117.0  56.0         3.8  111.0      2.5   
4  51.0     80.0     1.010    106.0  26.0         1.4    NaN      NaN   

   Hemoglobina  Packed cell volume  White blood cell count  \
0         15.4                44.0                  7800.0   
1         11.3                38.0                  6000.0   
2          9.6                31.0                  7500.0   
3         11.2                32.0                  6700.0   
4         11.6                35.0                  7300.0   

   Red blood cell count  
0                   5.2  
1                   NaN  
2                   NaN  
3                   3.9  
4                   4.6

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397 entries, 0 to 399
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Edad                    388 non-null    float64
 1   Presion                 386 non-null    float64
 2   Gravedad                351 non-null    float64
 3   Glucosa                 353 non-null    float64
 4   Urea                    378 non-null    float64
 5   Creatinina              380 non-null    float64
 6   Sodio                   310 non-null    float64
 7   Potasio                 309 non-null    float64
 8   Hemoglobina             346 non-null    float64
 9   Packed cell volume      327 non-null    float64
 10  White blood cell count  293 non-null    float64
 11  Red blood cell count    269 non-null    float64
dtypes: float64(12)
memory usage: 40.3 KB


Buscas los valores nulos para hacer imputación

In [13]:
valores_nulos = data.isnull().sum()
print(valores_nulos)
data.shape

Edad                        9
Presion                    11
Gravedad                   46
Glucosa                    44
Urea                       19
Creatinina                 17
Sodio                      87
Potasio                    88
Hemoglobina                51
Packed cell volume         70
White blood cell count    104
Red blood cell count      128
dtype: int64


(397, 12)

No podemos dejar celdas con valores vacíos, asi que los vamos a imputar con el promedio 

In [14]:
# Rellena los valores nulos de la edad con la media de la columna
media_edad = data['Edad'].mean()
data['Edad'] = data['Edad'].fillna(media_edad)


# Rellena los valores nulos de la presión con la media de la columna
media_presion = data['Presion'].mean()
data['Presion'] = data['Presion'].fillna(media_presion)

# Rellena los valores nulos de la gravedad con la media de la columna
media_gravedad = data['Gravedad'].mean()
data['Gravedad'] = data['Gravedad'].fillna(media_gravedad)

# Rellena los valores nulos de la glucosa con la media de la columna
media_glucosa = data['Glucosa'].mean()
data['Glucosa'] = data['Glucosa'].fillna(media_glucosa)

# Rellena los valores nulos de la urea con la media de la columna
media_urea = data['Urea'].mean()
data['Urea'] = data['Urea'].fillna(media_urea)

# Rellena los valores nulos de la creatinina con la media de la columna
media_creatinina = data['Creatinina'].mean()
data['Creatinina'] = data['Creatinina'].fillna(media_creatinina)

# Rellena los valores nulos del sodio con la media de la columna
media_sodio = data['Sodio'].mean()
data['Sodio'] = data['Sodio'].fillna(media_sodio)

# Rellena los valores nulos del potasio con la media de la columna
media_potasio = data['Potasio'].mean()
data['Potasio'] = data['Potasio'].fillna(media_potasio)

# Rellena los valores nulos de la hemoglobina con la media de la columna
media_hemo = data['Hemoglobina'].mean()
data['Hemoglobina'] = data['Hemoglobina'].fillna(media_hemo)

# Rellena los valores nulos del volumen células con la media de la columna
media_pcv = data['Packed cell volume'].mean()
data['Packed cell volume'] = data['Packed cell volume'].fillna(media_pcv)

# Rellena los valores nulos de las celulas blancas con la media de la columna
media_blanca = data['White blood cell count'].mean()
data['White blood cell count'] = data['White blood cell count'].fillna(media_blanca)

# Rellena los valores nulos de las celulas rojas con la media de la columna
media_rojo = data['Red blood cell count'].mean()
data['Red blood cell count'] = data['Red blood cell count'].fillna(media_rojo)

Volvemos a checar los valores faltantes

In [15]:
data.isnull().sum()

Edad                      0
Presion                   0
Gravedad                  0
Glucosa                   0
Urea                      0
Creatinina                0
Sodio                     0
Potasio                   0
Hemoglobina               0
Packed cell volume        0
White blood cell count    0
Red blood cell count      0
dtype: int64

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397 entries, 0 to 399
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Edad                    397 non-null    float64
 1   Presion                 397 non-null    float64
 2   Gravedad                397 non-null    float64
 3   Glucosa                 397 non-null    float64
 4   Urea                    397 non-null    float64
 5   Creatinina              397 non-null    float64
 6   Sodio                   397 non-null    float64
 7   Potasio                 397 non-null    float64
 8   Hemoglobina             397 non-null    float64
 9   Packed cell volume      397 non-null    float64
 10  White blood cell count  397 non-null    float64
 11  Red blood cell count    397 non-null    float64
dtypes: float64(12)
memory usage: 40.3 KB


In [17]:
# Exportar la nueva base
data.to_csv('clean_dataev2.csv', index=False)